pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: node
      image: node:10

trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: build
        container: node
        steps:
          - checkout: self
            clean: true
            displayName: Checkout Source
          - script: yarn install --frozen-lockfile
            displayName: Install using yarn with frozen lockfile
          - script: yarn build
            displayName: Build dev using yarn
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/dist/PlayChatUI"
              artifact: dist-dev
              publishLocation: pipeline
          - script: yarn build:prod
            displayName: Build production using yarn
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/dist/PlayChatUI"
              artifact: dist-prod
              publishLocation: pipeline
