name: Auto approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.ACTIONS_TOKEN }}"
      - uses: github-actions-up-and-running/pr-comment@v1.0.1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          repo-token: "${{ secrets.ACTIONS_TOKEN }}"
          message: "@dependabot merge"
